### ISSUE TITLE
Common checkstyle errors (pls take note!)

### ISSUE THREAD

**Issue by Weng-Kexin** [AY1920S1-CS2113T-F11-2/main#150]
- Comment indentations
- Using the '.*' form of import (should be avoided)
- Missing javadoc
- Missing '.' in javadoc
- Unused javadoc @ comment
- Line is longer than 120 characters
- Whitespace around 'if'
- '(' is preceded with whitespace
- Switch statement indentation

**Comment by omupenguin** [comment]
For the comment indentations, take note that the indentation from using CTRL+/ does not comply with checkstyle!
