### ISSUE TITLE
BUG: ASCII Art showing up as gibberish instead

### ISSUE THREAD

**Issue by omupenguin** [AY1920S1-CS2113T-F11-2/main#188]
![image](https://user-images.githubusercontent.com/42564029/67964394-2f661500-fc3b-11e9-865a-568b699e05d4.png)

**Comment by Weng-Kexin** [comment]
still printing gibberish

**Comment by Weng-Kexin** [comment]
![Screenshot_4](https://user-images.githubusercontent.com/42372486/67968235-fb422280-fc41-11e9-83e3-0e93adab82e6.png)
