### ISSUE TITLE
BUG: Incorrect outcome for modify if user input is incorrect

### ISSUE THREAD

**Issue by yetong1895** [AY1920S1-CS2113T-F11-2/main#191]
![image](https://user-images.githubusercontent.com/42373360/67967283-4eb37100-fc40-11e9-80cb-a01f26c0089f.png)
If user input multiple incorrect component, weird and incorrect UI is printed.

![image](https://user-images.githubusercontent.com/42373360/67967311-5b37c980-fc40-11e9-9001-200c20da1c26.png)
Modification for amount is successful even if input is incorrect.

**Comment by yetong1895** [comment]
Update: 
The first case happen when the first parameter is incorrect **type**(regardless of the correctness of the second parameter).

![image](https://user-images.githubusercontent.com/42373360/67967942-76570900-fc41-11e9-913c-67b6a2c4c085.png)
Another case is even if the first parameter is correct, both will not be updated if the second parameter is incorrect.

**Comment by omupenguin** [comment]
Thanks for the tip. 

> Another case is even if the first parameter is correct, both will not be updated if the second parameter is incorrect.

This behavior is intended. It is meant for the user to change what they want all at once rather than piece by piece.
