### ISSUE TITLE
About us page (admin)

### ISSUE THREAD

**Issue by Weng-Kexin** [AY1920S1-CS2113T-F11-2/main#9]
Use  [this](https://github.com/nusCS2113-AY1920S1/addressbook-level3/blob/master/docs/AboutUs.adoc) as reference for the format (follow closely!!)
Including the name/photo of the supervisor/lecturer is optional.
The photo of a team member should be doc/images/githbub_username_in_lower_case.png e.g. docs/images/johndoe.png. If you photo is in jpg format, name the file as .png anyway.
Indicate the different roles of each team member (refer to [this (admin -> project scope)](https://nuscs2113-ay1920s1.github.io/website/schedule/week6/project.html)

**Comment by omupenguin** [comment]
![image](https://user-images.githubusercontent.com/42564029/65161850-dc5d4780-da6a-11e9-8fe8-6d6575d6b694.png)
